### ISSUE TITLE
Bug when selecting a course (in CoEx starter) whose path was changed

### ISSUE THREAD

**Issue by kryzar** [dEAduction/dEAduction#67]
### Bug description

In the CoEx starter, choosing a file (from the *previous courses widget*) whose path was changed (red squared course in the hereunder screenshot) causes a bug:

<img width="562" alt="image" src="https://user-images.githubusercontent.com/31312212/112859036-bf1f2580-90b2-11eb-87be-1caeccfb56a8.png">

```txt
Traceback (most recent call last):
  File "SOME_PATH/dEAduction/src/deaduction/dui/stages/start_coex/start_coex_widgets.py", line 347, in __recent_course_clicked
    course = Course.from_file(course_path)
  File "SOME_PATH/dEAduction/src/deaduction/pylib/coursedata/course.py", line 141, in from_file
    file_content = course_path.read_text()
  File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1255, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1241, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1109, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'SOME_OTHER_PATH/exercises_theorie_des_ensembles.lean'
```

after that, the interface is unusable:

<img width="562" alt="image" src="https://user-images.githubusercontent.com/31312212/112859199-e2e26b80-90b2-11eb-9155-c367d3ef438d.png">

### How to reproduce the bug

1. Open dEAduction and a course from the files browser and start an exercise (important);
2. quit dEAduction;
3. change the course file's path (by putting it in another directory);
4. launch dEAduction and select this course in the *previous courses widget*.

### Environment

- OS and OS version: macOS Catalina 10.15.7
- d∃∀duction version (or commit ID): commit `66da32deffc29654b289150922c5727ec17b0c23` on branch `dev/integrate_start_coex2`.

### Fix ideas

Check if saved path exists before adding the course item to the *previous courses widget* and do not add it if the course does not exist. This solution may be not so great because usr may lose all statistics.

### Submission checklist

1. [X] d∃∀duction is up-to-date and this bug is in the latest version.
2. [X] I've checked that no-one reported this problem by browsing [other
   issues](https://github.com/dEAduction/dEAduction/issues).
3. [X] This issue deals with one and only one issue (if you have multiple
   issues, please open multiple issues).
4. [X] I correctly labeled my issue (see commented rules below).
5. [X] I want to fix this bug. (Check if yo do, no judgement if you do not!)

**Comment by FredericLeRoux** [comment]
A ce propos, signalé pr JG : "Encore un au sujet de l'historique des fichiers qui ne sauvegarde pas les bons path dans ".deaduction/config". La raison est que le path est hardcoded dans le pkl (ce qui est potentiellement moyennement une bonne idée, je sais pas), mais c'est cette version qui est inclue dans l'historique et pas le path réel.
"
